function [net, info] = trainModel(imds, cfg)
% TRAINMODEL Trains the convolutional network for diabetic retinopathy grading
if nargin < 2
    cfg = trainingConfig();
end

modelCfg = modelConfig();
lgraph = createModel(modelCfg);

if isstruct(imds) && isfield(imds, 'TrainingData')
    trainData = imds.TrainingData;
    valData = imds.ValidationData;
else
    trainData = imds;
    valData = [];
end

if ~isempty(valData)
    opts = trainingOptions('adam', ...
        'InitialLearnRate', cfg.initialLearnRate, ...
        'MaxEpochs', cfg.maxEpochs, ...
        'MiniBatchSize', cfg.miniBatchSize, ...
        'ValidationData', valData, ...
        'ValidationFrequency', 20, ...
        'ValidationPatience', 5, ...
        'Shuffle', 'every-epoch', ...
        'ExecutionEnvironment', cfg.executionEnvironment, ...
        'Plots', 'training-progress', ...
        'Verbose', true);
else
    opts = trainingOptions('adam', ...
        'InitialLearnRate', cfg.initialLearnRate, ...
        'MaxEpochs', cfg.maxEpochs, ...
        'MiniBatchSize', cfg.miniBatchSize, ...
        'Shuffle', 'every-epoch', ...
        'ExecutionEnvironment', cfg.executionEnvironment, ...
        'Plots', 'training-progress', ...
        'Verbose', true);
end

[net, info] = trainNetwork(trainData, lgraph, opts);

outDir = fileparts(cfg.outputModel);
if ~isempty(outDir) && ~exist(outDir, 'dir')
    mkdir(outDir);
end
save(cfg.outputModel, 'net', 'info', '-v7.3');
end
