import { DRClassInfo } from '@/types';

export const DR_CLASSES: DRClassInfo[] = [
  {
    id: 0,
    code: 'STAGE_0',
    name: 'No Apparent Diabetic Retinopathy',
    shortName: 'No DR',
    severity: 'normal',
    color: '#10b981',
    badgeBg: 'bg-emerald-500/10 dark:bg-emerald-500/20',
    badgeBorder: 'border-emerald-500/30',
    badgeText: 'text-emerald-700 dark:text-emerald-400',
    icdrCriteria: 'No visible retinal microvascular abnormalities. Normal fundus appearance.',
    pathology: ['Normal retinal vasculature', 'Intact macula & fovea', 'Clear optical disc margin'],
    recommendation: 'No DR detected. Maintain standard annual diabetic eye examination and optimal glycemic control (HbA1c < 7.0%).',
    urgency: 'Routine',
    followUp: 'Annual (12 Months)',
    referralRequired: false,
  },
  {
    id: 1,
    code: 'STAGE_1',
    name: 'Mild Non-Proliferative DR',
    shortName: 'Mild NPDR',
    severity: 'mild',
    color: '#06b6d4',
    badgeBg: 'bg-cyan-500/10 dark:bg-cyan-500/20',
    badgeBorder: 'border-cyan-500/30',
    badgeText: 'text-cyan-700 dark:text-cyan-400',
    icdrCriteria: 'Presence of Microaneurysms only. No hemorrhages, exudates, or IRMA present.',
    pathology: ['Isolated microaneurysms (< 5)', 'No macular edema', 'Normal optic disc'],
    recommendation: 'Early microvascular changes detected. Re-screen in 6-12 months. Review systemic hypertension, lipid profile, and glycemic control with primary care physician.',
    urgency: 'Elective',
    followUp: '6 - 12 Months',
    referralRequired: false,
  },
  {
    id: 2,
    code: 'STAGE_2',
    name: 'Moderate Non-Proliferative DR',
    shortName: 'Moderate NPDR',
    severity: 'moderate',
    color: '#f59e0b',
    badgeBg: 'bg-amber-500/10 dark:bg-amber-500/20',
    badgeBorder: 'border-amber-500/30',
    badgeText: 'text-amber-700 dark:text-amber-400',
    icdrCriteria: 'More than microaneurysms but less than severe NPDR (dot/blot hemorrhages, hard exudates, cotton wool spots).',
    pathology: ['Multiple microaneurysms', 'Dot & blot hemorrhages in 1-3 quadrants', 'Hard lipid exudates', 'Occasional cotton wool spots'],
    recommendation: 'Significant microvascular retinopathy present. Refer to an ophthalmologist for comprehensive dilated fundus examination and OCT macular thickness evaluation within 4-8 weeks.',
    urgency: 'Priority',
    followUp: '4 - 8 Weeks (Ophthalmology)',
    referralRequired: true,
  },
  {
    id: 3,
    code: 'STAGE_3',
    name: 'Severe Non-Proliferative DR',
    shortName: 'Severe NPDR',
    severity: 'severe',
    color: '#f97316',
    badgeBg: 'bg-orange-500/10 dark:bg-orange-500/20',
    badgeBorder: 'border-orange-500/30',
    badgeText: 'text-orange-700 dark:text-orange-400',
    icdrCriteria: 'Meets the 4-2-1 Rule: >20 intraretinal hemorrhages in each of 4 quadrants, OR definite venous beading in 2+ quadrants, OR prominent IRMA in 1+ quadrant.',
    pathology: ['Extensive 4-quadrant hemorrhages', 'Venous beading / caliber variations', 'Intraretinal microvascular abnormalities (IRMA)', 'High progression risk to PDR (>50% within 1 year)'],
    recommendation: 'High risk of imminent proliferative conversion or vision loss. Prompt referral to retina specialist within 2-4 weeks for consideration of pan-retinal photocoagulation (PRP) or anti-VEGF therapy.',
    urgency: 'Urgent',
    followUp: '2 - 4 Weeks (Retina Specialist)',
    referralRequired: true,
  },
  {
    id: 4,
    code: 'STAGE_4',
    name: 'Proliferative Diabetic Retinopathy',
    shortName: 'Proliferative DR (PDR)',
    severity: 'proliferative',
    color: '#ef4444',
    badgeBg: 'bg-red-500/10 dark:bg-red-500/20',
    badgeBorder: 'border-red-500/30',
    badgeText: 'text-red-700 dark:text-red-400',
    icdrCriteria: 'Neovascularization of the disc (NVD) or retina (NVE), preretinal/vitreous hemorrhage, or fibrovascular proliferation.',
    pathology: ['Neovascularization of disc (NVD) or elsewhere (NVE)', 'Pre-retinal / Vitreous hemorrhage risk', 'Fibrovascular tissue formation', 'Tractional retinal detachment risk'],
    recommendation: 'URGENT: Sight-threatening proliferative diabetic retinopathy. Immediate referral to vitreoretinal surgeon within 1-2 weeks. Urgent intervention required (anti-VEGF injections / PRP laser / vitrectomy).',
    urgency: 'Emergency',
    followUp: '1 - 2 Weeks (Emergency Vitreoretinal)',
    referralRequired: true,
  }
];
