import { SampleCase } from '@/types';

export const SAMPLE_CASES: SampleCase[] = [
  {
    id: 'sample-0',
    name: 'Case A - Normal Retinal Fundus (Stage 0)',
    patientId: 'PT-8942-01',
    age: 48,
    gender: 'Female',
    eye: 'OD (Right)',
    hba1c: 6.4,
    diabetesYears: 4,
    diabetesDuration: 4,
    trueStage: 0,
    qualityPassed: true,
    notes: 'Standard healthy fundus with sharp optic cup margin, intact foveal reflex, and clean vascular branching without microvascular lesions.',
    previewColor: '#991b1b',
    characteristics: {
      microaneurysms: 0,
      hemorrhages: 0,
      exudates: 0,
      cottonWoolSpots: 0,
      neovascularization: false,
      macularEdemaRisk: 'Low',
    }
  },
  {
    id: 'sample-1',
    name: 'Case B - Early Mild NPDR (Stage 1)',
    patientId: 'PT-7320-04',
    age: 56,
    gender: 'Male',
    eye: 'OS (Left)',
    hba1c: 7.8,
    diabetesYears: 9,
    diabetesDuration: 9,
    trueStage: 1,
    qualityPassed: true,
    notes: 'Subtle microaneurysms detected in the temporal superior arcade. No visible hemorrhages or exudates.',
    previewColor: '#7f1d1d',
    characteristics: {
      microaneurysms: 4,
      hemorrhages: 0,
      exudates: 0,
      cottonWoolSpots: 0,
      neovascularization: false,
      macularEdemaRisk: 'Low',
    }
  },
  {
    id: 'sample-2',
    name: 'Case C - Moderate NPDR with Hard Exudates (Stage 2)',
    patientId: 'PT-6109-12',
    age: 62,
    gender: 'Female',
    eye: 'OD (Right)',
    hba1c: 8.9,
    diabetesYears: 14,
    diabetesDuration: 14,
    trueStage: 2,
    qualityPassed: true,
    notes: 'Multiple microaneurysms, localized dot/blot hemorrhages, and lipid hard exudates forming a circinate ring near temporal macula.',
    previewColor: '#881337',
    characteristics: {
      microaneurysms: 18,
      hemorrhages: 7,
      exudates: 12,
      cottonWoolSpots: 1,
      neovascularization: false,
      macularEdemaRisk: 'Moderate',
    }
  },
  {
    id: 'sample-3',
    name: 'Case D - Severe NPDR 4-2-1 Rule (Stage 3)',
    patientId: 'PT-4591-08',
    age: 67,
    gender: 'Male',
    eye: 'OS (Left)',
    hba1c: 10.2,
    diabetesYears: 21,
    diabetesDuration: 21,
    trueStage: 3,
    qualityPassed: true,
    notes: 'Extensive multi-quadrant intraretinal hemorrhages, venous beading along superior arcade, and multiple soft cotton wool infarcts.',
    previewColor: '#581c87',
    characteristics: {
      microaneurysms: 45,
      hemorrhages: 28,
      exudates: 19,
      cottonWoolSpots: 6,
      neovascularization: false,
      macularEdemaRisk: 'High',
    }
  },
  {
    id: 'sample-4',
    name: 'Case E - Active Proliferative PDR (Stage 4)',
    patientId: 'PT-3302-19',
    age: 59,
    gender: 'Male',
    eye: 'OD (Right)',
    hba1c: 11.5,
    diabetesYears: 24,
    diabetesDuration: 24,
    trueStage: 4,
    qualityPassed: true,
    notes: 'Critical neovascularization of the disc (NVD > 1/3 disc area), preretinal flame hemorrhages, and fibrovascular tufts threatening visual acuity.',
    previewColor: '#450a0a',
    characteristics: {
      microaneurysms: 60,
      hemorrhages: 42,
      exudates: 34,
      cottonWoolSpots: 9,
      neovascularization: true,
      macularEdemaRisk: 'Severe',
    }
  },
  {
    id: 'sample-fail',
    name: 'Case F - Image Quality Assessment Failure (Poor Scan)',
    patientId: 'PT-1104-X9',
    age: 71,
    gender: 'Female',
    eye: 'OD (Right)',
    hba1c: 8.1,
    diabetesYears: 12,
    diabetesDuration: 12,
    trueStage: -1,
    qualityPassed: false,
    notes: 'Severe motion blur, low illumination, and media opacity (dense cataract) hindering fundus vessel visibility. Fails clinical screening threshold (IQA < 0.55).',
    previewColor: '#1c1917',
    characteristics: {
      microaneurysms: 0,
      hemorrhages: 0,
      exudates: 0,
      cottonWoolSpots: 0,
      neovascularization: false,
      macularEdemaRisk: 'Low',
    }
  }
];
